name: Build and Deploy to S3

on:
  push:
    branches:
      - quality
      - stage
      - production

jobs:
  get-environment:
    name: Get environment
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github code
      id: checkout-id
      uses: actions/checkout@v4
    - id: setenv
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          echo "my_env=stage" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/quality" ]]; then
          echo "my_env=quality" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
          echo "my_env=production" >> $GITHUB_OUTPUT
        fi
  build-deploy:
    runs-on: ubuntu-latest
    needs: get-environment
    environment: 
      name: ${{ needs.get-environment.outputs.my_env }}
    steps:
    - uses: actions/checkout@v4
    - name: Copy files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}